apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: apps
  labels:
    deployment: kustomize
    name: apps
    tier: cluster
  annotations:
    argocd.argoproj.io/sync-wave: "-200"
spec:
  project: cluster-addons
  source:
    repoURL: https://github.com/MavenWave-DevOps/shannon-test-gtiops.git
    path: apps
    targetRevision: main
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
    - CreateNamespace=true