apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: cert-manager
  
helmCharts:
- includeCRDs: true
  name: cert-manager
  namespace: cert-manager
  releaseName: cert-manager
  repo: https://charts.jetstack.io
  valuesFile: values.yaml
  version: 1.10.1

resources:
  - private-issuer.yaml



patches: 
 - path: gcp-sa-patches.yaml

