apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: cert-manager
  
helmCharts:
- includeCRDs: true
  name: cert-manager
  namespace: cert-manager
  releaseName: cert-manager
  repo: https://charts.jetstack.io
  valuesFile: values.yaml
  version: 1.10.1

patches:
- patch: "- op: add\n  path: /webhooks/0/namespaceSelector/matchExpressions/-\n  value:\n
    \   key: control-plane\n    operator: DoesNotExist  "
  target:
    group: admissionregistration.k8s.io
    kind: ValidatingWebhookConfiguration
    name: cert-manager-webhook
    version: v1
