apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: cert-manager
  
helmCharts:
- includeCRDs: true
  name: cert-manager
  namespace: cert-manager
  releaseName: cert-manager
  repo: https://charts.jetstack.io
  valuesFile: values.yaml
  version: 1.10.1

resources:
- https://github.com/jetstack/google-cas-issuer/releases/download/v0.6.2/google-cas-issuer-v0.6.2.yaml
- google-cas-issuer.yaml

patches:
- path: gcp-sa-patches.yaml

images:
- name: quay.io/jetstack/cert-manager-google-cas-issuer
  newTag: 0.6.2
