global:
  leaderElection:
    namespace: cert-manager
installCRDs: true

image:
  # -- Target image repository.
  repository: quay.io/jetstack/cert-manager-google-cas-issuer
  # -- Target image version tag.
  tag: 0.6.2
  # -- Kubernetes imagePullPolicy on Deployment.
  pullPolicy: IfNotPresent
