apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: projects
  namespace: argocd
  labels:
    deployment: manifests
    name: projects
  annotations:
    argocd.argoproj.io/sync-wave: "-100"
spec:
  project: cluster-addons
  source:
    repoURL: https://github.com/MavenWave-DevOps/shannon-test-gtiops.git
    path: dev/projects
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: false
      selfHeal: true