apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: jenkins
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: SecretStore
    name: jenkins

  target:
    creationPolicy: Owner
    template:
      data: 
        jenkins-admin-user: admin
        jenkins-admin-password: '{{ .jenkins_pwd }}'

  data:
  - secretKey: jenkins_pwd
    remoteRef:
      key: jenkins-pwd




  