apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: jenkins-admin-user
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: SecretStore
    name: jenkins

  target:
    creationPolicy: Owner
    template:
      data: 
        username: admin
        password: '{{ .jenkins-pwd }}'

  data:
  - secretKey: jenkins-pwd
    remoteRef:
      key: jenkins-pwd




  