apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: jenkins
spec:
   provider:
    gcpsm:
      projectID: sr-cas-gke-test
      auth:
        workloadIdentity:
          # name of the cluster region
          clusterLocation: us-central1-c
          # name of the GKE cluster
          clusterName: sr-cas-gke-test-usc1-cl01
          # projectID of the cluster (if omitted defaults to spec.provider.gcpsm.projectID)
          clusterProjectID: sr-cas-gke-test
          # reference the sa from above
          serviceAccountRef:
            name: jenkins
            namespace: jenkins